#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumaneSociety
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CustomerDatabase")]
	public partial class CustomerProfileDatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public CustomerProfileDatabaseDataContext() : 
				base(global::HumaneSociety.Properties.Settings.Default.CustomerDatabaseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CustomerProfileDatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CustomerProfileDatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CustomerProfileDatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CustomerProfileDatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CustomerProfile> CustomerProfiles
		{
			get
			{
				return this.GetTable<CustomerProfile>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CustomerProfiles")]
	public partial class CustomerProfile
	{
		
		private string _Name;
		
		private System.Nullable<int> _Age;
		
		private string _FavoriteAnimal;
		
		private string _FavoriteBreed;
		
		private System.Nullable<bool> _IsElegibleForAdopting;
		
		public CustomerProfile()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int")]
		public System.Nullable<int> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this._Age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FavoriteAnimal", DbType="VarChar(50)")]
		public string FavoriteAnimal
		{
			get
			{
				return this._FavoriteAnimal;
			}
			set
			{
				if ((this._FavoriteAnimal != value))
				{
					this._FavoriteAnimal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FavoriteBreed", DbType="VarChar(50)")]
		public string FavoriteBreed
		{
			get
			{
				return this._FavoriteBreed;
			}
			set
			{
				if ((this._FavoriteBreed != value))
				{
					this._FavoriteBreed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsElegibleForAdopting", DbType="Bit")]
		public System.Nullable<bool> IsElegibleForAdopting
		{
			get
			{
				return this._IsElegibleForAdopting;
			}
			set
			{
				if ((this._IsElegibleForAdopting != value))
				{
					this._IsElegibleForAdopting = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
